#!/usr/bin/env python3
"""Trusted Issue/PR lifecycle controller. GitHub text remains data throughout.

Only a fresh human write-level ``leaderboard-ready`` label event can generate a
candidate. A consumed label is not an approval of future edits. The authenticated
bot marker binds the last generated bytes and head; human commits freeze updates.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping
from urllib.parse import quote

ROOT = Path(__file__).resolve().parents[2]
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
READY = "leaderboard-ready"
BOT = "github-actions[bot]"
MARKER_PREFIX = "<!-- graphland-automation:v1\n"
MARKER_SUFFIX = "\n-->\n\nThis pending draft snapshot is owned by automation. Source edits require a fresh maintainer label; manual branch edits or marking ready for review freeze regeneration."
MAX_JSON = 128 * 1024
HEX40 = re.compile(r"^[0-9a-f]{40}$")
HEX64 = re.compile(r"^[0-9a-f]{64}$")
LOGIN = re.compile(r"^[A-Za-z0-9][A-Za-z0-9-]{0,38}$")
MARKER_KEYS = {"version", "issue", "state", "snapshot_sha256", "submission_sha256", "head_sha", "prior_head_sha", "prior_submission_sha256", "source_sha", "gate_actor", "pr_number"}
MANIFEST_KEYS = {"version", "issue", "outcome", "source_sha", "snapshot_sha256", "submission_sha256", "gate_actor", "message"}


class Skip(RuntimeError):
    """Expected lifecycle outcome: visible in run summary, never an error notice."""


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def json_bytes(value: Any) -> bytes:
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True, allow_nan=False) + "\n").encode("utf-8")


def load_bounded(path: Path, limit: int = MAX_JSON) -> Any:
    if path.is_symlink() or not path.is_file() or path.stat().st_size > limit:
        raise ValueError("Expected a bounded regular JSON file")
    return json.loads(path.read_bytes(), parse_constant=lambda _: (_ for _ in ()).throw(ValueError("Non-finite JSON")))


def snapshot(issue: Mapping[str, Any]) -> str:
    return digest(json_bytes({**{key: issue.get(key) for key in ("number", "title", "body", "created_at")}, "author": issue.get("user", {}).get("login")}))


def labels(issue: Mapping[str, Any]) -> set[str]:
    return {item["name"] if isinstance(item, dict) else item for item in issue.get("labels", [])}


def authorize(event: Mapping[str, Any], issue: Mapping[str, Any], permission: Mapping[str, Any]) -> str:
    if issue.get("state") != "open" or not {READY, "leaderboard-submission"}.issubset(labels(issue)):
        raise Skip("Issue is closed or its conversion gate is absent")
    if event.get("action") != "labeled" or event.get("label", {}).get("name") != READY:
        raise Skip("Issue edits require a fresh maintainer label; no automatic regeneration")
    if snapshot(event["issue"]) != snapshot(issue):
        raise Skip("Issue changed after the label event; remove and reapply leaderboard-ready after review")
    actor = event.get("sender", {})
    login = actor.get("login", "")
    if actor.get("type") != "User" or not LOGIN.fullmatch(login):
        raise Skip("Conversion requires a human maintainer")
    # GitHub maps maintain to coarse write and triage to read. Role names are
    # descriptive labels (including custom roles), never an authority signal.
    if permission.get("permission") not in {"write", "admin"}:
        raise Skip("Gate actor does not have write-level repository permission")
    return login


def marker_body(marker: Mapping[str, Any]) -> str:
    return MARKER_PREFIX + json.dumps(marker, sort_keys=True, separators=(",", ":")) + MARKER_SUFFIX


def trusted_marker(comments: list[dict[str, Any]], number: int) -> tuple[dict[str, Any] | None, int | None]:
    found = []
    for comment in comments:
        user = comment.get("user", {})
        body = comment.get("body", "")
        if user.get("login") != BOT or user.get("type") != "Bot" or not isinstance(body, str) or not body.startswith(MARKER_PREFIX) or not body.endswith(MARKER_SUFFIX):
            continue
        try:
            marker = json.loads(body[len(MARKER_PREFIX):-len(MARKER_SUFFIX)])
            valid = set(marker) == MARKER_KEYS and marker["version"] == 1 and marker["issue"] == number and marker["state"] in {"prepared", "generated"}
            valid = valid and all(HEX64.fullmatch(marker[key] or "") for key in ("snapshot_sha256", "submission_sha256"))
            valid = valid and all(HEX40.fullmatch(marker[key] or "") for key in ("head_sha", "source_sha"))
            valid = valid and (marker["prior_head_sha"] is None or HEX40.fullmatch(marker["prior_head_sha"]))
            valid = valid and (marker["prior_submission_sha256"] is None or HEX64.fullmatch(marker["prior_submission_sha256"]))
            valid = valid and LOGIN.fullmatch(marker["gate_actor"] or "") and (marker["pr_number"] is None or type(marker["pr_number"]) is int)
            if valid and body == marker_body(marker):
                found.append((comment["id"], marker))
        except (ValueError, TypeError, KeyError):
            continue
    if not found:
        return None, None
    identifier, marker = max(found, key=lambda item: item[0])
    return marker, identifier


def check_remote(marker: dict[str, Any] | None, head: str | None, data: bytes | None, pull: dict[str, Any] | None) -> None:
    if pull is not None and (pull.get("state") != "open" or pull.get("draft") is not True):
        raise Skip("The PR is closed or handed over to manual review; use a new Issue for a revision")
    if head is None:
        retry_before_initial_push = marker is not None and marker["state"] == "prepared" and marker["prior_head_sha"] is None and pull is None
        if (marker is not None or pull is not None) and not retry_before_initial_push:
            raise Skip("Previously generated branch is missing; do not recreate reviewed history")
        return
    if not marker or data is None:
        raise Skip("Existing branch has no authenticated bot ownership record; manual handover is frozen")
    current_hash = digest(data)
    same_generated = head == marker["head_sha"] and current_hash == marker["submission_sha256"]
    recover_prepared = marker["state"] == "prepared" and head == marker["prior_head_sha"] and current_hash == marker["prior_submission_sha256"]
    if not (same_generated or recover_prepared):
        raise Skip("Human commits or changed JSON detected; automatic regeneration is frozen")
    record = json.loads(data)
    if record.get("verification") != "self_reported" or record.get("review") != {"status": "pending", "reviewer_github": None, "reviewed_at": None, "notes": None}:
        raise Skip("Review or verification metadata was edited; automatic regeneration is frozen")


def run(args: list[str], root: Path = ROOT, *, binary: bool = False) -> Any:
    result = subprocess.run(args, cwd=root, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False)
    if result.returncode:
        # Never echo token-bearing URLs, raw provider responses, or submitted text.
        raise RuntimeError("Command failed: " + args[0])
    return result.stdout if binary else result.stdout.decode("utf-8").strip()


class GitHub:
    def __init__(self, repository: str):
        if not re.fullmatch(r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", repository):
            raise ValueError("Invalid repository name")
        self.repository = repository

    def api(self, path: str, method: str = "GET", payload: Any = None) -> Any:
        args = ["gh", "api", "-H", "Accept: application/vnd.github+json", "-H", "X-GitHub-Api-Version: 2022-11-28", "--method", method, "repos/" + self.repository + "/" + path]
        if payload is None:
            raw = run(args)
        else:
            with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", delete=False) as handle:
                json.dump(payload, handle)
                path_arg = handle.name
            try:
                raw = run(args + ["--input", path_arg])
            finally:
                Path(path_arg).unlink(missing_ok=True)
        if len(raw.encode("utf-8")) > 2 * 1024 * 1024:
            raise ValueError("GitHub response exceeded the bounded limit")
        return json.loads(raw) if raw else None

    def pages(self, path: str) -> list[dict[str, Any]]:
        result = []
        for page in range(1, 11):
            values = self.api(path + ("&" if "?" in path else "?") + "per_page=100&page=" + str(page))
            result.extend(values)
            if len(values) < 100:
                return result
        raise Skip("Issue history exceeded safe pagination limits; manual review is required")

    def permission(self, login: str) -> dict[str, Any]:
        return self.api("collaborators/" + quote(login, safe="") + "/permission")

    def pulls(self, branch: str) -> list[dict[str, Any]]:
        owner = self.repository.split("/")[0]
        values = self.pages("pulls?state=all&base=main&head=" + quote(owner + ":" + branch, safe=""))
        return [pull for pull in values if pull.get("head", {}).get("ref") == branch and (pull.get("head", {}).get("repo") or {}).get("full_name", "").casefold() == self.repository.casefold()]


def output(values: Mapping[str, Any]) -> None:
    path = os.environ.get("GITHUB_OUTPUT")
    if path:
        with open(path, "a", encoding="utf-8") as handle:
            for key, value in values.items():
                handle.write(key + "=" + str(value) + "\n")
    print(json.dumps(values, sort_keys=True))


def prepare(event: dict[str, Any], issue: dict[str, Any], permission: dict[str, Any], destination: Path, source_sha: str) -> dict[str, Any]:
    from issue_to_submission import IssueSubmissionError, submission_from_issue

    destination.mkdir(parents=True, exist_ok=True)
    manifest = {"version": 1, "issue": issue["number"], "outcome": "ready", "source_sha": source_sha, "snapshot_sha256": snapshot(issue), "submission_sha256": None, "gate_actor": event.get("sender", {}).get("login", ""), "message": ""}
    try:
        manifest["gate_actor"] = authorize(event, issue, permission)
        data = json_bytes(submission_from_issue(issue))
        manifest["submission_sha256"] = digest(data)
        (destination / "submission.json").write_bytes(data)
    except Skip as exc:
        manifest.update(outcome="skip", message=str(exc))
    except IssueSubmissionError as exc:
        manifest.update(outcome="invalid", message=str(exc)[:4000])
    (destination / "manifest.json").write_bytes(json_bytes(manifest))
    return manifest


def read_candidate(directory: Path, event: dict[str, Any], issue: dict[str, Any], permission: dict[str, Any], source_sha: str) -> tuple[dict[str, Any], bytes]:
    from issue_to_submission import submission_from_issue

    if directory.is_symlink() or not directory.is_dir() or {path.name for path in directory.iterdir()} != {"manifest.json", "submission.json"}:
        raise ValueError("Candidate artifact must contain exactly manifest.json and submission.json")
    manifest = load_bounded(directory / "manifest.json", 16 * 1024)
    record = load_bounded(directory / "submission.json")
    actor = authorize(event, issue, permission)
    if set(manifest) != MANIFEST_KEYS or manifest["version"] != 1 or manifest["outcome"] != "ready" or manifest["source_sha"] != source_sha or not HEX40.fullmatch(source_sha):
        raise Skip("Candidate source changed or its manifest is invalid")
    if manifest["issue"] != issue["number"] or manifest["gate_actor"] != actor or manifest["snapshot_sha256"] != snapshot(issue):
        raise Skip("Candidate does not match the freshly approved Issue snapshot")
    data = (directory / "submission.json").read_bytes()
    if digest(data) != manifest["submission_sha256"] or data != json_bytes(record) or data != json_bytes(submission_from_issue(issue)):
        raise ValueError("Candidate bytes do not equal the freshly parsed pending Issue")
    return manifest, data


def marker_write(client: GitHub, number: int, marker: dict[str, Any], comment_id: int | None) -> int:
    response = client.api("issues/comments/" + str(comment_id) if comment_id else "issues/" + str(number) + "/comments", "PATCH" if comment_id else "POST", {"body": marker_body(marker)})
    if response.get("user", {}).get("login") != BOT or response.get("body") != marker_body(marker):
        raise RuntimeError("Ownership marker readback did not match the authenticated bot")
    return response["id"]


def mutate(client: GitHub, event: dict[str, Any], directory: Path, root: Path = ROOT) -> dict[str, Any]:
    from validate import validate_repository

    number = event["issue"]["number"]
    branch = "leaderboard/issue-" + str(number)
    filename = "leaderboard/submissions/issue-" + str(number) + ".json"
    issue = client.api("issues/" + str(number))
    source_sha = run(["git", "rev-parse", "HEAD"], root)
    if client.api("commits/main")["sha"] != source_sha:
        raise Skip("Main changed after candidate validation; reapply the gate for a current candidate")
    manifest, data = read_candidate(directory, event, issue, client.permission(event.get("sender", {}).get("login", "")), source_sha)
    pulls = client.pulls(branch)
    if len(pulls) > 1:
        raise Skip("More than one stable-branch PR exists; manual review is required")
    pull = pulls[0] if pulls else None
    marker, comment_id = trusted_marker(client.pages("issues/" + str(number) + "/comments"), number)
    credential = "!f() { printf '%s\\n' 'username=x-access-token' \"password=$GH_TOKEN\"; }; f"
    git_remote = ["git", "-c", "credential.helper=" + credential]
    remote = run(git_remote + ["ls-remote", "--heads", "origin", "refs/heads/" + branch], root)
    head = remote.split()[0] if remote else None
    old_data = None
    if head:
        run(git_remote + ["fetch", "--no-tags", "origin", "refs/heads/" + branch + ":refs/remotes/origin/" + branch], root)
        base = run(["git", "merge-base", "HEAD", head], root)
        if run(["git", "diff", "--name-only", base, head], root).splitlines() != [filename]:
            raise Skip("Existing branch changes unexpected paths; manual handover is frozen")
        old_data = run(["git", "show", head + ":" + filename], root, binary=True)
        if len(old_data) > MAX_JSON:
            raise Skip("Existing branch record exceeds the safe size limit")
    check_remote(marker, head, old_data, pull)
    target = root / filename
    if target.exists() or target.is_symlink():
        raise Skip("Submission already exists in main; use a new Issue for a revision")
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    validate_repository(root, allow_pending=True)
    changes = run(["git", "status", "--porcelain=v1", "--untracked-files=all"], root).splitlines()
    if changes != ["?? " + filename]:
        raise RuntimeError("Refusing unexpected workspace changes")
    authorize(event, client.api("issues/" + str(number)), client.permission(event.get("sender", {}).get("login", "")))
    if client.api("commits/main")["sha"] != source_sha:
        raise Skip("Source changed before mutation; no branch was pushed")
    pushed = False
    if old_data == data and marker and marker["snapshot_sha256"] == manifest["snapshot_sha256"]:
        new_head = head
    else:
        run(["git", "switch", "--create", branch], root)
        run(["git", "config", "user.name", BOT], root)
        run(["git", "config", "user.email", "41898282+github-actions[bot]@users.noreply.github.com"], root)
        run(["git", "add", "--", filename], root)
        run(["git", "commit", "-m", "Update leaderboard submission for issue #" + str(number)], root)
        new_head = run(["git", "rev-parse", "HEAD"], root)
        prepared = {"version": 1, "issue": number, "state": "prepared", "snapshot_sha256": manifest["snapshot_sha256"], "submission_sha256": digest(data), "head_sha": new_head, "prior_head_sha": head, "prior_submission_sha256": digest(old_data) if old_data else None, "source_sha": source_sha, "gate_actor": manifest["gate_actor"], "pr_number": pull["number"] if pull else None}
        comment_id = marker_write(client, number, prepared, comment_id)
        before_push = client.pulls(branch)
        if len(before_push) > 1 or (before_push and (before_push[0].get("state") != "open" or before_push[0].get("draft") is not True)):
            raise Skip("PR was handed over before push; no branch was replaced")
        authorize(event, client.api("issues/" + str(number)), client.permission(event.get("sender", {}).get("login", "")))
        if client.api("commits/main")["sha"] != source_sha:
            raise Skip("Main changed before push; no branch was replaced")
        run(git_remote + ["push", "--force-with-lease=refs/heads/" + branch + ":" + (head or ""), "origin", "HEAD:refs/heads/" + branch], root)
        pushed = True
    # Re-read PR state after the push; only draft PRs are ever retained.
    try:
        latest = client.pulls(branch)
        if len(latest) > 1 or (latest and (latest[0].get("state") != "open" or latest[0].get("draft") is not True)):
            raise Skip("PR was handed over during generation")
        authorize(event, client.api("issues/" + str(number)), client.permission(event.get("sender", {}).get("login", "")))
    except Skip as exc:
        if pushed:
            raise Skip("Branch was already pushed as " + new_head + "; " + str(exc) + ". Data remain pending/self_reported. Inspect this head and request fresh review or close the PR.") from exc
        raise
    pull = latest[0] if latest else client.api("pulls", "POST", {"base": "main", "head": branch, "draft": True, "title": "[Leaderboard] Submission from issue #" + str(number), "body": "Generated from a maintainer-approved Issue snapshot.\n\nCloses #" + str(number) + "\n\nSnapshot SHA256: `" + manifest["snapshot_sha256"] + "`.\n\nThe conversion label is consumed. Source edits require a new maintainer label. Human branch edits or marking ready for review freeze regeneration."})
    generated = {"version": 1, "issue": number, "state": "generated", "snapshot_sha256": manifest["snapshot_sha256"], "submission_sha256": digest(data), "head_sha": new_head, "prior_head_sha": None, "prior_submission_sha256": None, "source_sha": source_sha, "gate_actor": manifest["gate_actor"], "pr_number": pull["number"]}
    marker_write(client, number, generated, comment_id)
    current = client.api("issues/" + str(number))
    if snapshot(current) == manifest["snapshot_sha256"] and READY in labels(current):
        client.api("issues/" + str(number) + "/labels/" + READY, "DELETE")
    return {"outcome": "generated", "pull_request": pull["number"], "head_sha": new_head}


def notify(client: GitHub, event: dict[str, Any], message: str) -> None:
    issue = client.api("issues/" + str(event["issue"]["number"]))
    authorize(event, issue, client.permission(event.get("sender", {}).get("login", "")))
    key = digest((snapshot(issue) + "\n" + message).encode("utf-8"))
    prefix = "<!-- graphland-error:v1 " + key + " -->"
    comments = client.pages("issues/" + str(issue["number"]) + "/comments")
    if any(item.get("user", {}).get("login") == BOT and item.get("user", {}).get("type") == "Bot" and item.get("body", "").startswith(prefix) for item in comments):
        return
    body = prefix + "\nLeaderboard conversion did not complete. Review the workflow run; correct this Issue and remove/reapply leaderboard-ready after review.\n\n" + message[:1000]
    client.api("issues/" + str(issue["number"]) + "/comments", "POST", {"body": body})


def deploy_check(current_sha: str, source_sha: str, rollback: bool, event_name: str, source_ref: str, rollback_sha: str = "") -> None:
    if source_ref != "refs/heads/main" or not HEX40.fullmatch(source_sha):
        raise Skip("Pages deployments must originate from main")
    if rollback and (event_name != "workflow_dispatch" or rollback_sha != source_sha or not HEX40.fullmatch(rollback_sha)):
        raise Skip("Rollback requires workflow_dispatch and the exact explicitly requested commit SHA")
    if current_sha != source_sha and not rollback:
        raise Skip("A newer main exists; this stale build will not replace the published site")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("prepare", "mutate", "notify", "select-source", "deploy-check", "build-info"))
    parser.add_argument("--event-json", type=Path)
    parser.add_argument("--candidate", type=Path)
    parser.add_argument("--staging", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--source-sha")
    parser.add_argument("--source-ref", default="refs/heads/main")
    parser.add_argument("--event-name", default="push")
    parser.add_argument("--rollback", action="store_true")
    parser.add_argument("--rollback-sha", default="")
    args = parser.parse_args()
    client = GitHub(os.environ["GITHUB_REPOSITORY"])
    try:
        if args.command in {"select-source", "deploy-check", "build-info"}:
            current_sha = client.api("commits/main")["sha"]
            selected_sha = (args.rollback_sha if args.rollback else current_sha) if args.command == "select-source" else args.source_sha
            if not args.rollback and args.rollback_sha:
                raise Skip("rollback_sha requires explicit rollback=true")
            deploy_check(current_sha, selected_sha, args.rollback, args.event_name, args.source_ref, args.rollback_sha)
            if args.rollback and client.api("compare/" + selected_sha + "...main").get("status") not in {"ahead", "identical"}:
                raise Skip("Rollback SHA must be an ancestor of current main")
            if args.command == "build-info":
                args.output.parent.mkdir(parents=True, exist_ok=True)
                args.output.write_bytes(json_bytes({"commit_sha": selected_sha, "source_ref": args.source_ref, "built_at": datetime.now(timezone.utc).isoformat().replace("+00:00", "Z"), "rollback": args.rollback}))
            output({"outcome": "current", "source_sha": selected_sha})
            return 0
        event = load_bounded(args.event_json, 512 * 1024)
        if args.command == "prepare":
            issue = client.api("issues/" + str(event["issue"]["number"]))
            permission = client.permission(event.get("sender", {}).get("login", "")) if event.get("action") == "labeled" else {}
            manifest = prepare(event, issue, permission, args.candidate, run(["git", "rev-parse", "HEAD"]))
            if event.get("action") == "edited" and manifest["outcome"] == "skip":
                previous, _ = trusted_marker(client.pages("issues/" + str(issue["number"]) + "/comments"), issue["number"])
                manifest["message"] = "Issue content is unchanged; no regeneration" if previous and previous["snapshot_sha256"] == snapshot(issue) else "Issue content changed; remove and reapply leaderboard-ready after maintainer review"
                (args.candidate / "manifest.json").write_bytes(json_bytes(manifest))
            if manifest["outcome"] == "ready":
                from validate import discover_submission_paths
                args.staging.mkdir(parents=True, exist_ok=True)
                for path in discover_submission_paths(ROOT / "leaderboard/submissions"):
                    shutil.copyfile(path, args.staging / path.name)
                shutil.copyfile(args.candidate / "submission.json", args.staging / ("issue-" + str(issue["number"]) + ".json"))
            output({"outcome": manifest["outcome"], "source_sha": manifest["source_sha"], "message": manifest["message"].replace("\n", " ")})
        elif args.command == "mutate":
            output(mutate(client, event, args.candidate))
        else:
            message = "A trusted workflow step failed. No automatic approval or merge was performed."
            if args.candidate and (args.candidate / "manifest.json").is_file():
                message = load_bounded(args.candidate / "manifest.json")["message"] or message
            notify(client, event, message)
    except Skip as exc:
        output({"outcome": "skip", "message": str(exc)})
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
